name          'petems-wercker_example'
version       '0.1.0'
source        ''
author        'petems'
license       'Apache 2.0'
summary       'An example of werker beaker tests'
description   ''
project_page  ''

dependency 'puppetlabs/stdlib'
